src/Ls/UserBundle/Entity/User.php
<?php

namespace Ls\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * @ORM\Entity(repositoryClass="Ls\UserBundle\Entity\UserRepository")
 * @ORM\Table(name="user")
 */
class User implements AdvancedUserInterface, \Serializable {

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=191, unique=true)
     * @var string
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=191, unique=true)
     * @var string
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $salt;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $password;

    /**
     * @var string
     */
    private $plain_password;

    /**
     * @ORM\Column(type="boolean")
     * @var boolean
     */
    private $active;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $last_login;

    /**
     * @ORM\Column(type="json_array")
     * @var string
     */
    private $roles;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $updated_at;

    /**
     * Constructor
     */
    public function __construct() {
        $this->active = false;
        $this->salt = md5(uniqid(null, true));
        $this->created_at = new \DateTime();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username) {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername() {
        return $this->username;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return User
     */
    public function setSalt($salt) {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Get salt
     *
     * @return string
     */
    public function getSalt() {
        return $this->salt;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password) {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword() {
        return $this->password;
    }

    /**
     * Set plain_password
     *
     * @param string $plain_password
     * @return User
     */
    public function setPlainPassword($plain_password) {
        $this->plain_password = $plain_password;

        return $this;
    }

    /**
     * Get plain_password
     *
     * @return string
     */
    public function getPlainPassword() {
        return $this->plain_password;
    }

    /**
     * Set active
     *
     * @param boolean $active
     * @return User
     */
    public function setActive($active) {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive() {
        return $this->active;
    }

    /**
     * Set last_login
     *
     * @param \DateTime $last_login
     * @return User
     */
    public function setLastLogin($last_login) {
        $this->last_login = $last_login;

        return $this;
    }

    /**
     * Get last_login
     *
     * @return \DateTime
     */
    public function getLastLogin() {
        return $this->last_login;
    }

    /**
     * Set roles
     *
     * @param array $roles
     * @return User
     */
    public function setRoles($roles) {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Get roles
     *
     * @return array
     */
    public function getRoles() {
        return $this->roles;
    }

    /**
     * Get roles
     *
     * @return array
     */
    static public function getRolesOptions() {
        $options = array(
            'Użytkownik' => 'ROLE_USER',
            'Administrator' => 'ROLE_ADMIN',
            'Umożliwia podszywanie się pod innego użytkownika' => 'ROLE_ALLOWED_TO_SWITCH',
        );
        return $options;
    }

    /**
     * Set created_at
     *
     * @param \DateTime $created_at
     * @return User
     */
    public function setCreatedAt($created_at) {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt() {
        return $this->created_at;
    }

    /**
     * Set updated_at
     *
     * @param \DateTime $updated_at
     * @return User
     */
    public function setUpdatedAt($updated_at) {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt() {
        return $this->updated_at;
    }

    public function eraseCredentials() {
    }

    public function isAccountNonExpired() {
        return true;
    }

    public function isAccountNonLocked() {
        return true;
    }

    public function isCredentialsNonExpired() {
        return true;
    }

    public function isEnabled() {
        return $this->active;
    }

    /** @see \Serializable::serialize() */
    public function serialize() {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->salt,
            $this->active
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized) {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->salt,
            $this->active
            ) = unserialize($serialized);
    }

    public function __toString() {
        if (is_null($this->getUsername())) {
            return 'NULL';
        }
        return $this->getUsername();
    }
}

src/Ls/UserBundle/Resources/views/Admin/batch.html.twig
{% extends '::backend.html.twig' %}

{% block body %}
    {% for flashMessage in app.session.flashbag.get('error') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Błąd!</strong> {{ flashMessage }}
                </div>
            </div>
        </div>
    {% endfor %}

    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Sukces!</strong> {{ flashMessage }}
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="row">
        <div class="col-sm-8">{{ wo_render_breadcrumbs() }}</div>
        <div class="col-sm-4 text-right" style="margin-bottom: 20px;">
            <a href="{{ path('ls_admin_user') }}" class="btn btn-default">
                <i class="glyphicon glyphicon-list"></i>
                Powrót do listy
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h1>Potwierdź wykonanie akcji</h1>

            <p>{{ message }}</p>

            <div class="well well-sm">
                <form class="form-inline" action="{{ path('ls_admin_user_batch_execute') }}" method="post">
                    <input type="hidden" name="action" value="{{ action }}" />
                    <input type="hidden" name="ids" value="{{ ids }}" />
                    <button type="submit" class="btn btn-danger">Tak, wykonaj</button>
                    <a href="{{ path('ls_admin_user') }}" class="btn btn-success">Nie, wróć do listy</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/Ls/UserBundle/Resources/views/Admin/edit.html.twig
{% extends '::backend.html.twig' %}
{% form_theme form with 'LsCoreBundle:Backend:fields.html.twig' %}

{% block body %}
    {% for flashMessage in app.session.flashbag.get('error') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Błąd!</strong> {{ flashMessage }}
                    {{ form_errors(form.username) }}
                    {{ form_errors(form.email) }}
                    {{ form_errors(form.plain_password) }}
                    {{ form_errors(form.roles) }}
                </div>
            </div>
        </div>
    {% endfor %}

    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Sukces!</strong> {{ flashMessage }}
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="row">
        <div class="col-sm-8">{{ wo_render_breadcrumbs() }}</div>
        <div class="col-sm-4 text-right" style="margin-bottom: 20px;">
            <a href="{{ path('ls_admin_user') }}" class="btn btn-default">
                <i class="glyphicon glyphicon-list"></i>
                Powrót do listy
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            {{ form_start(form, {'attr': {'id': form.vars.name, 'class': 'form-horizontal', 'novalidate': 'novalidate' }}) }}
            <ul class="nav nav-tabs pills">
                <li class="active">
                    <a data-toggle="tab" href="#tab-general">Administrator</a>
                </li>
            </ul>

            <div class="tab-content" style="margin-top: 15px;">
                <div id="tab-general" class="tab-pane active">
                    <div class="form-group{% if form.username.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.username, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.username, {'attr': {'class': 'form-control' }}) }}
                            {% if form.username.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group{% if form.email.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.email, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.email, {'attr': {'class': 'form-control' }}) }}
                            {% if form.email.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group{% if form.plain_password.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.plain_password, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.plain_password, {'attr': {'class': 'form-control' }}) }}
                            {% if form.plain_password.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group{% if form.roles.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.roles, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.roles) }}
                            {% if form.roles.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            {{ form_widget(form.active) }}
                        </div>
                    </div>
                </div>
            </div>
            <div style="border-top: 1px solid #ddd; margin-bottom: 15px;"></div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary' }}) }}
                    {{ form_widget(form.submit_and_list, {'attr': {'class': 'btn btn-default' }}) }}
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

src/Ls/UserBundle/Resources/views/Admin/index.html.twig
{% extends '::backend.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).on('change', '#limit-select', function () {
            var limit = $(this).val();
            $.ajax({
                type: 'post',
                url: '{{ path('ls_admin_user_set_limit') }}',
                data: {
                    'limit': limit
                },
                success: function (response) {
                    window.location.pathname = '{{ path('ls_admin_user') }}';
                }
            });
        });
    </script>
{% endblock %}

{% block body %}
    {% for flashMessage in app.session.flashbag.get('error') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Błąd!</strong> {{ flashMessage }}
                </div>
            </div>
        </div>
    {% endfor %}

    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Sukces!</strong> {{ flashMessage }}
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="row">
        <div class="col-sm-8">{{ wo_render_breadcrumbs() }}</div>
        <div class="col-sm-4 text-right" style="margin-bottom: 20px;">
            <a href="{{ path('ls_admin_user_new') }}" class="btn btn-default">
                <i class="glyphicon glyphicon-plus"></i>
                Dodaj
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            {% if entities|length > 0 %}
                <div class="panel panel-default table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th class="check">
                                <input type="checkbox" class="select-all">
                            </th>
                            <th>
                                {{ knp_pagination_sortable(entities, 'Nazwa konta', 'e.username') }}
                                {% if entities.isSorted('e.username') and entities.getDirection() == 'asc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet"></span>{% endif %}
                                {% if entities.isSorted('e.username') and entities.getDirection() == 'desc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>{% endif %}
                            </th>
                            <th>
                                {{ knp_pagination_sortable(entities, 'Adres e-mail', 'e.email') }}
                                {% if entities.isSorted('e.email') and entities.getDirection() == 'asc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet"></span>{% endif %}
                                {% if entities.isSorted('e.email') and entities.getDirection() == 'desc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>{% endif %}
                            </th>
                            <th>
                                {{ knp_pagination_sortable(entities, 'Aktywne', 'e.enabled') }}
                                {% if entities.isSorted('e.enabled') and entities.getDirection() == 'asc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet"></span>{% endif %}
                                {% if entities.isSorted('e.enabled') and entities.getDirection() == 'desc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>{% endif %}
                            </th>
                            <th>
                                {{ knp_pagination_sortable(entities, 'Data utworzenia', 'e.created_at') }}
                                {% if entities.isSorted('e.created_at') and entities.getDirection() == 'asc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet"></span>{% endif %}
                                {% if entities.isSorted('e.created_at') and entities.getDirection() == 'desc' %}
                                    <span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>{% endif %}
                            </th>
                            <th>Opcje</th>
                        </tr>
                        </thead>
                        <form action="{{ path('ls_admin_user_batch') }}" method="post">
                            <tbody>
                            {% for entity in entities %}
                                <tr>
                                    <td class="check">
                                        <input type="checkbox" class="ids" name="ids[]" value="{{ entity.id }}">
                                    </td>
                                    <td class="text">{{ entity.username }}</td>
                                    <td class="text">{{ entity.email }}</td>
                                    <td class="text">
                                        {% if entity.enabled %}
                                            <span class="text-success">Tak</span>
                                        {% else %}
                                            <span class="text-danger">Nie</span>
                                        {% endif %}
                                    </td>
                                    {% spaceless %}
                                    {% endspaceless %}
                                    <td class="text">{{ entity.createdat|localizeddate('long', 'none') }}</td>
                                    <td class="text-right opcje">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                            <a href="{{ path('ls_admin_user_edit',{'id': entity.id}) }}" title="Edytuj">
                                                <i class="glyphicon glyphicon-edit"></i>
                                            </a>
                                            <a href="#" data-href="{{ path('ls_admin_user_delete',{'id': entity.id}) }}" class="btn-delete" title="Usuń" data-toggle="modal" data-target="#confirm-delete">
                                                <i class="glyphicon glyphicon-remove"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="6">
                                    <div class="form-inline">
                                        <div class="pull-left">
                                            <span>Zaznaczone</span>
                                            <select class="form-control" name="action">
                                                <option value="delete">Usuń</option>
                                            </select>
                                            <button type="submit" class="btn btn-primary">Ok</button>
                                        </div>
                                        <div class="pull-right">
                                            <span>Strona {{ page }} z {{ entities.getPageCount }} - {{ entities.getTotalItemCount }} wyników - na stronie</span>
                                            <select id="limit-select" class="form-control">
                                                <option value="15"{% if limit == 15 %} selected="selected"{% endif %}>15</option>
                                                <option value="25"{% if limit == 25 %} selected="selected"{% endif %}>25</option>
                                                <option value="50"{% if limit == 50 %} selected="selected"{% endif %}>50</option>
                                                <option value="100"{% if limit == 100 %} selected="selected"{% endif %}>100</option>
                                                <option value="150"{% if limit == 150 %} selected="selected"{% endif %}>150</option>
                                                <option value="200"{% if limit == 200 %} selected="selected"{% endif %}>200</option>
                                            </select>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% if entities.getPageCount > 1 %}
                                <tr>
                                    <td class="pagination-container" colspan="6">
                                        {{ knp_pagination_render(entities) }}
                                    </td>
                                </tr>
                            {% endif %}
                            </tfoot>
                        </form>
                    </table>
                </div>
            {% else %}
                <h4 class="text-center">Brak elementów w bazie</h4>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block modals %}
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"><h4>Usuwanie użykownika</h4></div>
                <div class="modal-body">Czy napewno chcesz usunąć tego użytkownika?</div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Anuluj</button>
                    <a href="#" class="btn btn-danger btn-ok-delete">Usuń</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Ls/UserBundle/Resources/views/Admin/new.html.twig
{% extends '::backend.html.twig' %}
{% form_theme form with 'LsCoreBundle:Backend:fields.html.twig' %}

{% block body %}
    {% for flashMessage in app.session.flashbag.get('error') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Błąd!</strong> {{ flashMessage }}
                    {{ form_errors(form.username) }}
                    {{ form_errors(form.email) }}
                    {{ form_errors(form.plain_password) }}
                    {{ form_errors(form.roles) }}
                </div>
            </div>
        </div>
    {% endfor %}

    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <strong>Sukces!</strong> {{ flashMessage }}
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="row">
        <div class="col-sm-8">{{ wo_render_breadcrumbs() }}</div>
        <div class="col-sm-4 text-right" style="margin-bottom: 20px;">
            <a href="{{ path('ls_admin_user') }}" class="btn btn-default">
                <i class="glyphicon glyphicon-list"></i>
                Powrót do listy
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            {{ form_start(form, {'attr': {'id': form.vars.name, 'class': 'form-horizontal', 'novalidate': 'novalidate' }}) }}
            <ul class="nav nav-tabs pills">
                <li class="active">
                    <a data-toggle="tab" href="#tab-general">Użytkownik</a>
                </li>
            </ul>

            <div class="tab-content" style="margin-top: 15px;">
                <div id="tab-general" class="tab-pane active">
                    <div class="form-group{% if form.username.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.username, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.username, {'attr': {'class': 'form-control' }}) }}
                            {% if form.username.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group{% if form.email.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.email, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.email, {'attr': {'class': 'form-control' }}) }}
                            {% if form.email.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group{% if form.plain_password.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.plain_password, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.plain_password, {'attr': {'class': 'form-control' }}) }}
                            {% if form.plain_password.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group{% if form.roles.vars.errors|length %} has-error has-feedback{% endif %}">
                        {{ form_label(form.roles, null, {'label_attr': {'class': 'col-sm-3 control-label' }}) }}
                        <div class="col-sm-9">
                            {{ form_widget(form.roles) }}
                            {% if form.roles.vars.errors|length %}
                                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3 control-label"><label>Inne opcje</label></div>
                        <div class="col-sm-9">
                            {{ form_widget(form.active) }}
                        </div>
                    </div>
                </div>
            </div>
            <div style="border-top: 1px solid #ddd; margin-bottom: 15px;"></div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary' }}) }}
                    {{ form_widget(form.submit_and_list, {'attr': {'class': 'btn btn-default' }}) }}
                    {{ form_widget(form.submit_and_new, {'attr': {'class': 'btn btn-default' }}) }}
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}